### ISSUE TITLE
branch wip_trac_30787

### ISSUE THREAD

**Issue by dimpase** [sagemath/p_group_cohomology#6]
it tracks work done on https://trac.sagemath.org/ticket/30787
A new release should be based on it.

**Comment by dimpase** [comment]
@mkoeppe - almost done on branch wip_trac_30787 (fixed installation of everything to Python directory via MANIFEST.in, making  the tarball for the package is a bit annoying though.

We probably should make 2 tarballs, one for modular_resolution, and one for the rest.

**Comment by dimpase** [comment]
https://github.com/sagemath/p_group_cohomology/tree/wip_trac_30787

**Comment by mkoeppe** [comment]
I recommend not to use `include_package_data` but rather to list `package_data` in setup.py or setup.cfg again

**Comment by mkoeppe** [comment]
Yes, the tarball for our `p_group_cohomology` package should just be the sdist generated by `setup.py sdist`.

**Comment by mkoeppe** [comment]
and the tarball for `modular_resolution` should be the one generated by `make distcheck` in the `present/` directory

**Comment by dimpase** [comment]
OK, I think it works now, refactored, in the newly released version 3.3.3
